"""Post-ingest summarization: a holistic, topic-grouped digest of what just
landed, generated by an LLM agent and shown to the user (and optionally dropped
into the cognitive-ledger inbox for later fact promotion).

Wired into `yaams ingest` and on by default. Reuses the pluggable LLM adapter
from `yaams.synthesize.llm` so the same backends (claude / codex / ollama /
subprocess) are available. Defaults to the `claude` CLI so it works out of the
box without configuring `synth`.

Everything here degrades gracefully: no new items, no backend, a dead CLI, or a
missing `ledger` install each short-circuit to a one-line note rather than
failing the ingest run.
"""

from __future__ import annotations

import json
import subprocess
from dataclasses import dataclass
from datetime import datetime

from yaams.synthesize.llm import llm_adapter_from_config
from yaams.time import parse_iso_datetime, to_local

# ponytail: hard caps so a big run (e.g. 374 new iMessages) can't blow up the
# prompt. Tune via summary.max_items / summary.content_chars in config.
DEFAULT_MAX_ITEMS = 400
DEFAULT_CONTENT_CHARS = 300


@dataclass
class SummaryResult:
  text: str | None  # the digest, or None when nothing was produced
  note: str | None = None  # one-line reason when text is None (shown to user)
  backend: str | None = None
  model: str | None = None
  inbox_path: str | None = None  # where it was filed, if to_inbox succeeded


def summary_config(cfg: dict) -> dict:
  """Resolve the `summary:` config block with defaults.

  `backend: synth` is a sentinel meaning "reuse whatever synth.backend is",
  so a user who already configured synth doesn't repeat themselves.
  """
  s = dict(cfg.get("summary", {}) or {})
  backend = (s.get("backend") or "claude").strip().lower()
  if backend == "synth":
    synth = cfg.get("synth", {}) or {}
    backend = (synth.get("backend") or "dummy").strip().lower()
    s = {**synth, **s, "backend": backend}
  return {
    "enabled": bool(s.get("enabled", True)),
    "backend": backend,
    "model": s.get("model"),
    "timeout": float(s.get("timeout") or 180.0),
    "host": s.get("host"),
    "command": s.get("command"),
    "max_items": int(s.get("max_items") or DEFAULT_MAX_ITEMS),
    "content_chars": int(s.get("content_chars") or DEFAULT_CONTENT_CHARS),
    "to_inbox": bool(s.get("to_inbox", True)),
    # claude backend only: run with --safe-mode so the user's global CLAUDE.md /
    # skills / hooks don't leak into the digest. On by default.
    "safe_mode": bool(s.get("safe_mode", True)),
  }


def build_sender_aliases(cfg: dict) -> dict[str, str]:
  """Map casefolded alias/canonical -> canonical name from the entity dict.

  The dictionary is already loaded into cfg by `load_config`; we reuse it to
  turn a raw sender (a bare phone number like ``+4794324297``, an email, a
  Signal service id) into the person's name. Read-time resolution mirrors how
  aliases already expand at query time — the raw store is left untouched.

  ponytail: exact casefold match. Phone formats vary (+47… vs 94… vs spaced);
  match works because we control the seeded aliases. Normalize on both sides if
  numbers start arriving in mixed formats.
  """
  dictionary = (cfg.get("entities") or {}).get("dictionary") or []
  amap: dict[str, str] = {}
  for entry in dictionary:
    if not isinstance(entry, dict):
      continue
    canonical = str(entry.get("canonical", "")).strip()
    if not canonical:
      continue
    amap.setdefault(canonical.casefold(), canonical)
    for alias in entry.get("aliases") or []:
      alias = str(alias).strip()
      if alias:
        amap.setdefault(alias.casefold(), canonical)
  return amap


def resolve_sender(sender: str | None, aliases: dict[str, str]) -> str:
  """Canonical name for a raw sender, or the raw value unchanged if unknown."""
  if not sender:
    return sender or ""
  return aliases.get(sender.strip().casefold(), sender)


def humanize_elapsed(seconds: float) -> str:
  """Coarse 'how long ago' bucket for staleness signalling."""
  if seconds < 0:
    return "in the future"
  minutes = int(seconds // 60)
  if minutes < 1:
    return "just now"
  if minutes < 60:
    return f"~{minutes}m ago"
  hours = minutes / 60
  if hours < 48:
    return f"~{round(hours)}h ago"
  return f"~{round(hours / 24)}d ago"


def fetch_new_items(
  conn,
  since: datetime,
  *,
  max_items: int,
  content_chars: int,
  now: datetime,
  sender_aliases: dict[str, str] | None = None,
) -> list[dict]:
  """Rows ingested at or after `since` (this run), newest last, capped.

  `ingested_at` is stamped when the Item is created during extraction, so
  `>= run_start` selects exactly this run's new rows. Content is truncated and
  newlines flattened to keep the prompt bounded.

  `sender` is resolved through the entity dictionary (phone/email -> name) and
  each item carries a pre-computed local time + elapsed ("~5h ago") so the LLM
  reports the anchor instead of doing date arithmetic (which it botches) — this
  is what keeps relative phrases in the content ("om 1-2 timer") from being
  echoed as if still true hours after the message was sent.
  """
  aliases = sender_aliases or {}
  rows = conn.execute(
    """
    SELECT source, timestamp, sender, subject, content
    FROM items
    WHERE ingested_at >= ?
    ORDER BY timestamp
    LIMIT ?
    """,
    (since.isoformat(), max_items),
  ).fetchall()
  out = []
  for r in rows:
    content = (r["content"] or "").replace("\n", " ").strip()
    if len(content) > content_chars:
      content = content[:content_chars] + "…"
    ts_raw = r["timestamp"] or ""
    when = ts_raw[:10]
    if ts_raw:
      try:
        ts = parse_iso_datetime(ts_raw)
        when = (
          f"{to_local(ts).strftime('%Y-%m-%d %H:%M')} "
          f"({humanize_elapsed((now - ts).total_seconds())})"
        )
      except ValueError:
        pass
    out.append({
      "source": r["source"],
      "date": when,
      "sender": resolve_sender(r["sender"], aliases),
      "subject": (r["subject"] or "").strip(),
      "content": content,
    })
  return out


def build_prompt(items: list[dict], *, total_new: int, now: datetime) -> str:
  """A holistic, topic-grouped digest prompt — cross-source, not per-source."""
  by_source: dict[str, list[dict]] = {}
  for it in items:
    by_source.setdefault(it["source"], []).append(it)

  lines: list[str] = []
  for source in sorted(by_source):
    lines.append(f"\n## source: {source} ({len(by_source[source])} item(s))")
    for it in by_source[source]:
      subj = f" | {it['subject']}" if it["subject"] else ""
      lines.append(f"- [{it['date']}] {it['sender']}{subj}: {it['content']}")

  shown = len(items)
  cap_note = (
    f"\n\n(Showing {shown} of {total_new} new items; the rest were truncated.)"
    if total_new > shown else ""
  )

  now_local = to_local(now).strftime("%Y-%m-%d %H:%M %Z")
  return (
    "You are summarizing a batch of personal/work data just ingested into a "
    "memory system. Write a tight, skimmable briefing for the owner (a "
    "Norwegian consultant) of what's new since last ingest.\n\n"
    f"It is now {now_local}. Each item is tagged with when it was sent and how "
    "long ago (e.g. '~5h ago') — this is often HOURS after the fact, because "
    "ingest runs on a delay.\n\n"
    "Rules:\n"
    "- Group by topic/theme across sources, NOT by source.\n"
    "- Anchor time to reality. A relative phrase INSIDE a message ('om 1-2 "
    "timer', 'later today', 'i morgen') is relative to when that message was "
    "SENT, not now. Combine it with the item's 'ago' tag and say what it means "
    "as of now — e.g. a message from ~5h ago saying guests arrive 'om 1-2 "
    "timer' means they likely arrived ~3-4h ago, so frame it as done, not "
    "pending. Flag anything whose deadline has probably already passed.\n"
    "- Lead with what still needs action NOW under a clearly flagged section; "
    "don't put already-elapsed events there.\n"
    "- Also surface leaked secrets, credentials, money, or access issues if any.\n"
    "- Use short markdown sections with bold topic headers and terse bullets.\n"
    "- Norwegian content stays in Norwegian; don't translate names. Senders are "
    "already resolved to names where known; use them as given.\n"
    "- Be concrete (names, times, projects). Skip filler. No preamble.\n"
    f"\nHere are the {shown} new items:\n"
    + "\n".join(lines)
    + cap_note
  )


def summarize_ingest(
  conn,
  cfg: dict,
  *,
  run_started_at: datetime,
  total_new: int,
) -> SummaryResult:
  """Build and run the post-ingest summary. Never raises — failures become a
  `note` so the ingest run still reports success."""
  sc = summary_config(cfg)
  if not sc["enabled"]:
    return SummaryResult(text=None, note="disabled in config")
  if total_new <= 0:
    return SummaryResult(text=None, note="no new items")
  if sc["backend"] == "dummy":
    return SummaryResult(
      text=None,
      note="summary backend is 'dummy'; set summary.backend (e.g. claude) to enable",
    )

  items = fetch_new_items(
    conn,
    run_started_at,
    max_items=sc["max_items"],
    content_chars=sc["content_chars"],
    now=run_started_at,
    sender_aliases=build_sender_aliases(cfg),
  )
  if not items:
    return SummaryResult(text=None, note="no new items found to summarize")

  adapter = llm_adapter_from_config({"synth": {
    "backend": sc["backend"],
    "model": sc["model"],
    "timeout": sc["timeout"],
    "host": sc["host"],
    "command": sc["command"],
    "safe_mode": sc["safe_mode"],
  }})
  prompt = build_prompt(items, total_new=total_new, now=run_started_at)
  try:
    resp = adapter.complete(prompt, max_tokens=1500, temperature=0.0)
  except FileNotFoundError:
    return SummaryResult(
      text=None,
      note=f"summary backend '{sc['backend']}' CLI not found on PATH",
      backend=sc["backend"],
    )
  except (subprocess.TimeoutExpired, subprocess.SubprocessError, RuntimeError) as exc:
    return SummaryResult(
      text=None,
      note=f"summary generation failed: {type(exc).__name__}: {exc}",
      backend=sc["backend"],
    )
  except Exception as exc:  # never let summarization sink the ingest result
    return SummaryResult(
      text=None,
      note=f"summary generation failed: {type(exc).__name__}: {exc}",
      backend=sc["backend"],
    )

  text = (resp.text or "").strip()
  if not text:
    return SummaryResult(text=None, note="summary backend returned nothing",
                         backend=resp.backend, model=resp.model)

  result = SummaryResult(text=text, backend=resp.backend, model=resp.model)
  if sc["to_inbox"]:
    result.inbox_path = write_summary_to_inbox(text, when=run_started_at)
  return result


def _ledger_inbox_dir() -> str | None:
  """Resolve the cognitive-ledger inbox via `ledger paths --json`. None if the
  CLI is absent or fails — the digest still prints, just isn't filed."""
  try:
    out = subprocess.run(
      ["ledger", "paths", "--json"],
      capture_output=True, text=True, timeout=15,
    )
  except (FileNotFoundError, subprocess.SubprocessError):
    return None
  if out.returncode != 0:
    return None
  try:
    notes_dir = json.loads(out.stdout).get("ledger_notes_dir")
  except (json.JSONDecodeError, AttributeError):
    return None
  return notes_dir


def write_summary_to_inbox(text: str, *, when: datetime) -> str | None:
  """Drop the digest into the ledger inbox (00_inbox) as a dated note for
  later triage. Returns the path, or None on any failure (best-effort)."""
  from pathlib import Path

  notes_dir = _ledger_inbox_dir()
  if not notes_dir:
    return None
  inbox = Path(notes_dir).expanduser() / "00_inbox"
  try:
    inbox.mkdir(parents=True, exist_ok=True)
  except OSError:
    return None
  iso = when.isoformat(timespec="seconds")
  path = inbox / f"note__ingest_summary_{when.strftime('%Y_%m_%d_%H%M%S')}.md"
  body = (
    f"---\n"
    f"created: {iso}\n"
    f"updated: {iso}\n"
    f"tags: [ingest, summary, digest]\n"
    f"confidence: 0.6\n"
    f"source: assistant\n"
    f"scope: meta\n"
    f"lang: en\n"
    f"---\n\n"
    f"# Ingest summary {when.strftime('%Y-%m-%d %H:%M')}\n\n"
    f"_Auto-generated digest of newly-ingested items. Promote durable facts, "
    f"then reject the rest._\n\n"
    f"{text}\n"
  )
  try:
    path.write_text(body, encoding="utf-8")
  except OSError:
    return None
  return str(path)
